apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tona2h52w-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tona2h52w-java-springboot-gitops